[package]
name = "rsssh"
version = "0.1.0"
authors = ["Sean McGivern <sean.mcgivern@rightscale.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
libc = "0.2"
cookie = "0.2"
hyper = "0.7.0"
